"""
core/risk_engine.py

Intelligent SOC Risk Scoring Engine.
Synthesizes 5 pillars: ML, Behaviour, Threat Intel, Historical, and Temporal
into a deterministic, explainable risk score (0-100).
"""

import json
import re
from pathlib import Path
from typing import Dict, Any, List
from collections import deque

class RiskScoringEngine:
    def __init__(self, config_path: str = "config/risk_weights.json"):
        # Load weights from config
        self.config_path = Path(config_path)
        if self.config_path.exists():
            with open(self.config_path, "r") as f:
                self.config = json.load(f)
        else:
            # Fallback defaults
            self.config = {
                "ml_weight": 0.25,
                "behaviour_weight": 0.20,
                "threat_intel_weight": 0.25,
                "historical_weight": 0.15,
                "temporal_weight": 0.15,
                "thresholds": {"critical": 80, "high": 60, "medium": 40, "low": 20}
            }
            
        # Threat Intel Regexes
        self.b64_pattern = re.compile(r'([A-Za-z0-9+/]{30,}={0,2})')
        self.suspicious_cmds = ["-enc", "-ExecutionPolicy Bypass", "wget", "curl", "Invoke-WebRequest", "/etc/shadow", "chmod 777"]
        self.malicious_ports = [4444, 3389, 22, 23] # Assuming external access to these is bad
        
        # State buffers for Temporal/Historical (In-memory, truncated to prevent leak)
        self.user_history = {}
        self.host_history = {}
        # Sliding window for temporal chains (last 1000 events)
        self.temporal_window = deque(maxlen=1000)

    def score(self, log_entry: Dict[str, Any], ml_confidence: float, features: Dict[str, float]) -> Dict[str, Any]:
        """
        Scores a single log entry.
        
        Args:
            log_entry: The raw Kibana log dictionary.
            ml_confidence: The confidence score (0.0 to 1.0) from the ML Ensemble Engine.
            features: The numeric features generated by the FeatureEngineeringPipeline for this log.
        """
        contributors = []
        mitre_tags = set()
        actions = set()
        explanation_points = []
        
        # 1. Machine Learning Signals (0-100)
        ml_score = ml_confidence * 100
        if ml_score > 60:
            contributors.append({"pillar": "Machine Learning", "score": ml_score, "detail": "High ML ensemble anomaly confidence."})
            explanation_points.append("was flagged by multiple ML anomaly detection models")
            
        # 2. Behaviour Signals (0-100)
        # Using feature values from the pipeline
        behaviour_score = 0.0
        b_details = []
        if features.get("_ml_user_is_new", 0) > 0:
            behaviour_score += 30
            b_details.append("New user detection")
            explanation_points.append("logged in as a completely new user")
        if features.get("_ml_ip_is_new", 0) > 0:
            behaviour_score += 20
            b_details.append("New IP detection")
            explanation_points.append("originated from a previously unseen IP address")
        if features.get("_ml_process_suspicious_cmd", 0) > 0:
            behaviour_score += 50
            b_details.append("Suspicious command structure")
            explanation_points.append("executed an obfuscated or suspicious command")
        if features.get("_ml_user_failed_login_ratio", 0) > 0.5:
            behaviour_score += 40
            b_details.append("High failed login ratio")
            explanation_points.append("triggered multiple authentication failures")
            
        behaviour_score = min(100, behaviour_score)
        if behaviour_score > 0:
            contributors.append({"pillar": "Behavioural", "score": behaviour_score, "detail": ", ".join(b_details)})
            
        # 3. Threat Intelligence (0-100)
        ti_score = 0.0
        ti_details = []
        cmdline = str(log_entry.get("process.command_line", log_entry.get("message", "")))
        port = log_entry.get("destination.port")
        
        if self.b64_pattern.search(cmdline):
            ti_score += 60
            ti_details.append("Base64 payload detected")
            mitre_tags.add("T1027 (Obfuscated Files or Information)")
            actions.add("Isolate endpoint immediately")
            explanation_points.append("utilized a Base64 encoded payload")
            
        for scmd in self.suspicious_cmds:
            if scmd.lower() in cmdline.lower():
                ti_score += 40
                ti_details.append(f"Suspicious keyword: {scmd}")
                mitre_tags.add("T1059 (Command and Scripting Interpreter)")
                actions.add("Review process tree")
                explanation_points.append(f"executed known suspicious command '{scmd}'")
                break
                
        if port in self.malicious_ports:
            ti_score += 30
            ti_details.append(f"Suspicious port connection: {port}")
            mitre_tags.add("T1043 (Commonly Used Port)")
            actions.add("Block port at firewall")
            explanation_points.append(f"connected to sensitive port {port}")
            
        ti_score = min(100, ti_score)
        if ti_score > 0:
            contributors.append({"pillar": "Threat Intelligence", "score": ti_score, "detail": ", ".join(ti_details)})
            
        # 4. Historical Context (0-100)
        hist_score = 0.0
        h_details = []
        user = log_entry.get("user.name", "unknown")
        host = log_entry.get("host.name", "unknown")
        
        # Simple asset criticality simulation
        if host.startswith("DC-") or host.startswith("PROD-"):
            hist_score += 50
            h_details.append("Target is a highly critical asset")
            mitre_tags.add("T1484 (Domain Policy Modification Target)")
            actions.add("Escalate to Tier 3 Incident Response")
            explanation_points.append("targeted a critical production asset")
            
        # Check if user has historically high risk
        past_user_risk = self.user_history.get(user, 0)
        if past_user_risk > 80:
            hist_score += 40
            h_details.append("User has a history of high-risk behavior")
            explanation_points.append("is an account with a history of severe security violations")
            
        hist_score = min(100, hist_score)
        if hist_score > 0:
            contributors.append({"pillar": "Historical Context", "score": hist_score, "detail": ", ".join(h_details)})

        # 5. Temporal Correlation (0-100)
        temp_score = 0.0
        t_details = []
        # Analyze the sliding window for attack chains
        auth_fails = sum(1 for e in self.temporal_window if e.get("user") == user and e.get("is_auth_fail"))
        if features.get("_ml_event_is_auth_failure", 0) == 0 and auth_fails >= 3:
            # We have a success following multiple failures
            temp_score += 80
            t_details.append("Brute-force success pattern")
            mitre_tags.add("T1110 (Brute Force)")
            actions.add("Force password reset and revoke active sessions")
            explanation_points.append("successfully authenticated immediately following a brute-force sequence")
            
        temp_score = min(100, temp_score)
        if temp_score > 0:
            contributors.append({"pillar": "Temporal Correlation", "score": temp_score, "detail": ", ".join(t_details)})
            
        # Update State Buffers
        self.temporal_window.append({
            "user": user,
            "host": host,
            "is_auth_fail": features.get("_ml_event_is_auth_failure", 0) > 0
        })

        # Calculate Final Risk
        w = self.config
        final_risk = (
            (w["ml_weight"] * ml_score) +
            (w["behaviour_weight"] * behaviour_score) +
            (w["threat_intel_weight"] * ti_score) +
            (w["historical_weight"] * hist_score) +
            (w["temporal_weight"] * temp_score)
        )
        
        # Ensure bounds
        final_risk = min(100.0, max(0.0, final_risk))
        
        # Update historical user risk (EMA)
        self.user_history[user] = (self.user_history.get(user, final_risk) * 0.9) + (final_risk * 0.1)

        # Map Risk Level
        if final_risk >= w["thresholds"]["critical"]:
            level = "Critical"
        elif final_risk >= w["thresholds"]["high"]:
            level = "High"
        elif final_risk >= w["thresholds"]["medium"]:
            level = "Medium"
        elif final_risk >= w["thresholds"]["low"]:
            level = "Low"
        else:
            level = "Info"
            
        # Generate Explanation
        if len(explanation_points) == 0:
            explanation = "Event occurred within normal baseline parameters with no significant threat indicators."
        elif len(explanation_points) == 1:
            explanation = f"Risk increased because the activity {explanation_points[0]}."
        else:
            explanation = f"Risk increased because the activity {', '.join(explanation_points[:-1])}, and {explanation_points[-1]}."

        return {
            "risk_score": int(final_risk),
            "risk_level": level,
            "confidence": int(ml_confidence * 100), # Using ML confidence as a proxy for detection confidence
            "top_contributors": sorted(contributors, key=lambda x: x["score"], reverse=True),
            "recommended_action": list(actions)[0] if actions else "Standard log review",
            "mapped_mitre": list(mitre_tags),
            "analyst_explanation": explanation
        }
